Update usda_sql_rules.yml
AmbitGroupvienna/usda-fns-ingest pull request #1
Opened 2018-06-01 15:37 UTC by whitneypeters

Updated 120W-124W. I got in a little over my head on 122W, so I didn't attempt 123W. I'll wait to do any more until you take a look at these.

2018-06-06 00:23 UTC, catherinedevlin commented on usda_fns_ingestor/usda_sql_rules.yml
> +  code: _16_vc1_forcause <= (_16_41A_free_doc_apps + _16_42A_free_inc_apps + _16_43A_rp_inc_apps)
Yup, just like this!

2018-06-06 00:23 UTC, catherinedevlin commented on usda_fns_ingestor/usda_sql_rules.yml
> +    and _16_32B_dc_snap_stud < 10
The counterpart to "fail when 3-2B > 10" isn't "succeed when 3-2B < 10 ", it's "succeed when 3-2B <= 10 " - or else this rule will say "fail" when 3-2B = 10.

That goes for all the < in this rule.

2018-06-06 00:23 UTC, catherinedevlin commented on usda_fns_ingestor/usda_sql_rules.yml
> +    and _16_33B_dc_other_stud < 10
The original rule says "fail when A and B and C and D", so to reverse that, it isn't "succeed when (not A) and (not B) and (not C) and (not D) - the ANDs have to turn into ORs, because if it only fails when any one of those things happen, it succeeds when any of those *do not* happen... does that make sense?

One shortcut to these is just to leave all the logic exactly as it is, and wrap the whole thing in a great big NOT ().  I did that on an earlier rule because reversing the complex combinations of ANDs and ORs was breaking my brain.

2018-06-06 00:23 UTC, catherinedevlin commented on usda_fns_ingestor/usda_sql_rules.yml
> +  code: _16_57A_confirmverf_apps < 15
The notes on 122W, below, apply here too.

2018-06-06 00:23 UTC, catherinedevlin commented on usda_fns_ingestor/usda_sql_rules.yml
> +  code: _16_57A_confirmverf_apps < 15
The notes on 122W, below, apply here too.

2018-06-06 14:04 UTC, whitneypeters commented on usda_fns_ingestor/usda_sql_rules.yml
> +    and _16_32B_dc_snap_stud < 10
It's like I've never done math before. Ugh. And thanks.

2018-06-06 16:52 UTC, catherinedevlin commented on usda_fns_ingestor/usda_sql_rules.yml
> +    and _16_32B_dc_snap_stud < 10
Don't sweat it, boolean logic can be not ((not (not easy))) sometimes.

2018-06-09 04:31 UTC, catherinedevlin requested changes
This is great!  Thank you for all this work.  I only spotted one typo.

2018-06-09 04:31 UTC, catherinedevlin commented on usda_fns_ingestor/usda_sql_rules.yml
> +        _16_54_error ^= (_16_42A_free_inc_apps + _16_43A_rp_inc_apps)
Forgot to change this `^=` to `<>` or `!=`

2018-06-13 17:25 UTC, whitneypeters commented
I forgot that I skipped check 56 - I need to look up syntax for rounding up and then will update it.

2018-06-14 15:54 UTC, Jkrzy commented
I rebased this onto @OpenGlobe's changes from #2 and resubmitted this as PR #4, lets collaborate there.

2018-06-14 15:54 UTC, closed without merging